apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/clusterissuer: "{{ .Values.app.name }}-selfsigned-cluster-issuer"   #annotation reference of cluster-issuer
    ingress.kubernetes.io/ssl-redirect: "true"    #annotation for redirection over HTTPS
  name: prometheus-grafana-ingress
  namespace: prometheus  #must be the same namespace where kube-prometheus stack is installed
spec:
  {{ .Values.prometheusGrafanaIngressSpec | toYaml | nindent 2}}