apiVersion: v1
data:                                # This is only for illustration purpose. The preservation &  Injection of secrets must be done through a Secretmanagement solution in a newr=prod/prod env.
  password: bW9uZ29kYi1wYXNzd29yZA== #mongodb-password
  username: bW9uZ29kYi11c2VybmFtZQ== #mongodb-username
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds