apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: prometheus-selfsigned-tls
spec:
 secretName: prometheus-tls-key-pair
 isCA: true
 issuerRef:
   name: {{ .Values.app.name }}-selfsigned-cluster-issuer
   kind: ClusterIssuer
 commonName: ingress.com
 dnsNames:
 - prometheus.ingress.com
 - ingress.com
